export const weatherTypeCodeDisplay = {
  "0": "Sunny",
  "1": "Sunny",
  "2": "Sunny",
  "3": "Cloudy",
  "45": "Cloudy",
  "48": "Cloudy",
  "51": "Rainy",
  "53": "Rainy",
  "55": "Rainy",
  "56": "Rainy",
  "57": "Rainy",
  "61": "Rainy",
  "63": "Rainy",
  "65": "Rainy",
  "66": "Rainy",
  "67": "Rainy",
  "71": "Snowy",
  "73": "Snowy",
  "75": "Snowy",
  "77": "Snowy",
  "80": "Rainy",
  "81": "Rainy",
  "82": "Rainy",
  "85": "Snowy",
  "86": "Snowy",
  "95": "Rainy",
  "96": "Rainy",
  "99":"Rainy",
};