export const weatherTypeCodeDisplay = {
  "0": "Clear skies",
  "1": "Mainly Clear",
  "2": "Partly cloudy",
  "3": "Overcast",
  "45": "Foggy",
  "48": "Foggy",
  "51": "Light drizzle",
  "53": "Moderate drizzle",
  "55": "Dense drizzle",
  "56": "Light Freezing drizzle",
  "57": " Dense Freezing drizzle",
  "61": "Slight Rain",
  "63": "Moderate Rain",
  "65": "Heavy Rain",
  "66": "Freezing Rain (Light)",
  "67": "Freezing Rain (Heavy)",
  "71": "Light Snow Fall",
  "73": "Moderate Snow Fall",
  "75": "Heavy Snow Fall",
  "77": "Snow Grains",
  "80": "Rain Showers (Slight)",
  "81": "Rain Showers (Moderate)",
  "82": "Rain Showers (Violent)",
  "85": "Snow Showers (Slight)",
  "86": "Snow Showers (Heavy)",
  "95": "Thunderstorm (Slight or moderate)",
  "96": "Thunderstorm with slight hail",
  "99":"Thunderstorm with heavy hail",
}